# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1
orbs:
  node: circleci/node@4.7
  aws-code-deploy: circleci/aws-code-deploy@2.0.0
  cypress: cypress-io/cypress@1.29.0

workflows:
  test:
    jobs:
      - node/test:
          version: '16.10'
          pkg-manager: yarn
      - cypress/run:
          start: yarn test
          yarn: true